(define (cloudify-maze filename-in filename-out new-width new-height)
  (let* ((image    (car (gimp-file-load RUN-NONINTERACTIVE filename-in "")))
         (drawable (car (gimp-image-active-drawable image)))
        )

     (gimp-image-scale image new-width new-height)
	 (plug-in-colortoalpha RUN-NONINTERACTIVE image drawable '(0 0 0))
	 (plug-in-gauss RUN-NONINTERACTIVE image drawable 8 8 0)
	 (plug-in-gauss RUN-NONINTERACTIVE image drawable 8 8 0)
     (gimp-selection-all image)
     (gimp-edit-paste drawable FALSE)
     (let* ((floatsel (car (gimp-edit-paste drawable FALSE))))
        (plug-in-cubism RUN-NONINTERACTIVE image drawable 10 2.5 1)
        (gimp-floating-sel-anchor floatsel)
     )
	 (plug-in-cubism RUN-NONINTERACTIVE image drawable 10 2.5 1)
	 (plug-in-gauss RUN-NONINTERACTIVE image drawable 8 8 0)
	 (plug-in-gauss RUN-NONINTERACTIVE image drawable 8 8 0)
     (gimp-selection-all image)
     (gimp-edit-paste drawable FALSE)
     (let* ((floatsel (car (gimp-edit-paste drawable FALSE))))
        (gimp-floating-sel-anchor floatsel)
     )
     (gimp-file-save RUN-NONINTERACTIVE image drawable filename-out "")
  )
)
